#!/usr/bin/env perl
use strict;
use warnings;
use Web::Scraper;
use WWW::Mechanize;
use Data::Printer;
use lib './BC';
use BC::UserProfile;

binmode STDOUT, ':utf8';

my $user = 'theraccoonbear';

my $bc = new BC::UserProfile(user => $user);
my $collection = $bc->pullCollection();
p($collection);